// File generated by `flutterfire configure`.
// Run: flutterfire configure
// Then replace this file with the generated one.
// See: https://firebase.flutter.dev/docs/core/usage

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    throw UnsupportedError(
      'DefaultFirebaseOptions have not been configured. '
      'Run `flutterfire configure` in the project root.',
    );
  }
}
